namespace EFCoreSqlPreview.Core.Generation;

/// <summary>
/// The fixed harness the generated worker is built from: the capture interceptor, the synthetic-row reader,
/// the DbContext activation ladder and the JSON output protocol.
/// </summary>
/// <remarks>
/// <para>
/// The template is a plain string rather than an embedded resource so the netstandard2.0 assembly needs no
/// resource lookup and the text is diffable in source control.
/// </para>
/// <para>
/// Several properties of this text were established empirically and must not be "tidied":
/// <c>FieldCount</c> is 1024 because a narrower reader fails split queries with "the underlying reader doesn't
/// have as many fields as expected" and <c>int.MaxValue</c> throws <c>OutOfMemoryException</c>; the reader
/// yields exactly one synthetic row because a zero-row reader makes every aggregate terminal throw; and
/// <c>PublishAot=false</c> is required or EF refuses to build the model at all.
/// </para>
/// </remarks>
public static class WorkerTemplate
{
    /// <summary>Placeholder for the <c>#:project</c> directive lines.</summary>
    public const string ProjectDirectivesPlaceholder = "{{PROJECT_DIRECTIVES}}";

    /// <summary>Placeholder for the <c>#:package</c> directive lines, empty in the auto-detect case.</summary>
    public const string PackageDirectivesPlaceholder = "{{PACKAGE_DIRECTIVES}}";

    /// <summary>Placeholder for the user's re-emitted using directives.</summary>
    public const string UserUsingsPlaceholder = "{{USER_USINGS}}";

    /// <summary>Placeholder for the type passed to <c>typeof</c> when activating the context.</summary>
    public const string ContextTypePlaceholder = "{{CONTEXT_TYPE}}";

    /// <summary>Placeholder for the type the activated context is cast to before the query runs.</summary>
    public const string ContextCastTypePlaceholder = "{{CONTEXT_CAST_TYPE}}";

    /// <summary>Placeholder for the free-variable declarations and replayed statements.</summary>
    public const string FreeVariablesPlaceholder = "{{FREE_VARIABLES}}";

    /// <summary>Placeholder for the <c>Observe*</c> call wrapping the user's query.</summary>
    public const string ObserveCallPlaceholder = "{{OBSERVE_CALL}}";

    /// <summary>Placeholder for the generated <c>OnConfiguring</c> subclass, empty when it is not needed.</summary>
    public const string DerivedContextPlaceholder = "{{DERIVED_CONTEXT}}";

    /// <summary>Placeholder for the forced dialect name, or the literal <c>null</c> when auto-detecting.</summary>
    public const string DialectPlaceholder = "{{DIALECT}}";

    /// <summary>Placeholder for the <c>UseXxx</c> call on the options builder.</summary>
    public const string ProviderConfigPlaceholder = "{{PROVIDER_CONFIG}}";

    /// <summary>Placeholder for the harmless connection string literal.</summary>
    public const string ConnectionStringPlaceholder = "{{CONNECTION_STRING}}";

    /// <summary>Placeholder for the shared <c>#:property</c> block.</summary>
    public const string PropertyDirectivesPlaceholder = "{{PROPERTY_DIRECTIVES}}";

    /// <summary>Marks the start of the JSON payload on stdout.</summary>
    public const string BeginSentinel = "<<<EFSQLPREVIEW-BEGIN>>>";

    /// <summary>Marks the end of the JSON payload on stdout.</summary>
    public const string EndSentinel = "<<<EFSQLPREVIEW-END>>>";

    /// <summary>Prefix used by the discovery worker to report one candidate context type.</summary>
    public const string ContextCandidatePrefix = "EFSP-CONTEXT-CANDIDATE: ";

    /// <summary>The MSBuild properties every worker needs, one <c>#:property</c> per line.</summary>
    /// <remarks>
    /// <c>PublishAot=false</c> is load-bearing. Nullable and analyzer settings only keep stdout clean, which
    /// matters because build output and the payload share the same stream.
    /// </remarks>
    public const string PropertyDirectives = """
#:property PublishAot=false
#:property Nullable=disable
#:property TreatWarningsAsErrors=false
#:property EnableNETAnalyzers=false
#:property AnalysisMode=None
#:property GenerateDocumentationFile=false
#:property NoWarn=$(NoWarn);CS0168;CS0219;CS1998;CS8600;CS8602;CS8603;CS8604;CS8618;CS8625;CS8632;CS8669;NU1608;NU1701;NU1903
""";

    /// <summary>
    /// The full worker program with placeholders unfilled.
    /// </summary>
    public const string Source = """
// <auto-generated> EF Core SQL Preview worker. Regenerated on every run; do not edit. </auto-generated>
{{PROJECT_DIRECTIVES}}
{{PACKAGE_DIRECTIVES}}
{{PROPERTY_DIRECTIVES}}

using System.Collections;
using System.Data.Common;
using System.Globalization;
using System.Reflection;
using System.Text;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Design;
using Microsoft.EntityFrameworkCore.Diagnostics;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
{{USER_USINGS}}

// ---------------------------------------------------------------------------------------------------------
// Top-level statements must precede every type declaration (CS8803), so the harness types are at the bottom.
// Never introduce an identifier named `args`: top-level statements already declare one.
// ---------------------------------------------------------------------------------------------------------
var __efspReport = await Preview.RunAsync(
    contextType: typeof({{CONTEXT_TYPE}}),
    body: async (__efspRawContext, __efspProbe) =>
    {
        var __efspCtx = ({{CONTEXT_CAST_TYPE}})__efspRawContext;

{{FREE_VARIABLES}}

        return {{OBSERVE_CALL}};
    });

// Exit code 0 whenever a payload exists, including a failed one: a non-zero exit is the extension's signal
// that the build itself broke and there is nothing to parse.
Preview.Emit(__efspReport);
return 0;

{{DERIVED_CONTEXT}}

public static class Preview
{
    public const string Begin = "<<<EFSQLPREVIEW-BEGIN>>>";
    public const string End = "<<<EFSQLPREVIEW-END>>>";

    // Deliberately not const: a const null would make the dialect checks compile-time constants and every
    // branch behind them unreachable code, which litters stdout with CS0162 next to the payload.
    public static readonly string Dialect = {{DIALECT}};
    public const string Neutral = {{CONNECTION_STRING}};

    public static void ConfigureProvider(DbContextOptionsBuilder b) => {{PROVIDER_CONFIG}};

    public static void Emit(Report report)
    {
        try { Console.OutputEncoding = Encoding.UTF8; } catch { }
        var json = JsonSerializer.Serialize(report, new JsonSerializerOptions
        {
            WriteIndented = false,
            Encoder = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
        });
        Console.Out.Write(Begin);
        Console.Out.Write(json);
        Console.Out.Write(End);
        Console.Out.WriteLine();
        Console.Out.Flush();
    }

    public static async Task<Report> RunAsync(Type contextType, Func<DbContext, Probe, Task<ResultInfo>> body)
    {
        var report = new Report { contextType = contextType.FullName };

        // Rung 1 materializes a synthetic row, which is what stops aggregate terminals throwing and lets a
        // split query issue all of its commands. Rung 2 feeds a real discriminator value for TPH models.
        // Rung 3 gives up on materialization and always runs, at the cost of partial split-query capture.
        var rungs = new[]
        {
            new Rung("SyntheticRow", 1, ""),
            new Rung("SyntheticRowTph", 1, null),
            new Rung("NoRows", 0, ""),
        };

        Attempt best = null;
        foreach (var rung in rungs)
        {
            var attempt = new Attempt { rung = rung.Name };
            var probe = new Probe { Rows = rung.Rows, StringValue = rung.StringValue };
            var interceptor = new CaptureInterceptor(probe);
            DbContext ctx = null;
            try
            {
                ctx = ContextActivator.Create(contextType, interceptor, report);
                if (rung.StringValue == null)
                {
                    var discriminator = FirstDiscriminatorValue(ctx);
                    if (discriminator == null) continue;
                    probe.StringValue = discriminator;
                }

                report.provider = ProviderShortName(ctx.Database.ProviderName);
                report.providerAssembly = ctx.Database.ProviderName;
                report.connectionString = Sanitize(ctx.Database.GetConnectionString());
                probe.Model = ctx.Model;
                attempt.result = await body(ctx, probe);
            }
            catch (PreviewActivationException activationFailure)
            {
                attempt.error = activationFailure.Message;
                attempt.errorKind = "ContextActivationFailed";
                attempt.commands = probe.Captured;
                best = attempt;
                break;
            }
            catch (Exception ex)
            {
                var unwrapped = Unwrap(ex);
                attempt.error = unwrapped.GetType().Name + ": " + unwrapped.Message;
                attempt.errorKind = Classify(unwrapped);
                attempt.detail = Detail(unwrapped);
            }
            finally
            {
                try { ctx?.Dispose(); } catch { }
            }

            attempt.commands = probe.Captured;
            if (best == null
                || attempt.commands.Count > best.commands.Count
                || (attempt.commands.Count == best.commands.Count && best.error != null && attempt.error == null))
            {
                best = attempt;
            }

            if (attempt.error == null && attempt.commands.Count > 0) break;
        }

        report.commands = best.commands;
        report.result = best.result;
        report.captureMode = best.rung;

        // Capturing at least one command is the definition of success: aggregate terminals and hostile
        // mappings can still throw afterwards, long after the SQL the user asked for was fully built.
        report.success = best.commands.Count > 0;

        if (!report.success)
        {
            report.error = best.error ?? "The query produced no SQL command.";
            report.errorKind = best.errorKind ?? "Unknown";
        }
        else
        {
            if (best.rung == "NoRows")
            {
                report.warnings.Add(
                    "This model could not materialize a synthetic row (a TPH discriminator or a JSON-mapped owned entity), "
                    + "so the query ran against an empty result set. If it is a split query, only the first of its commands is shown.");
            }

            if (best.error != null)
            {
                report.warnings.Add("SQL was captured, but the run ended with: " + best.error
                    + (best.detail == null ? "" : " (" + best.detail + ")"));
            }
        }

        return report;
    }

    private static string FirstDiscriminatorValue(DbContext ctx)
    {
        foreach (var entityType in ctx.Model.GetEntityTypes())
        {
            if (entityType.FindDiscriminatorProperty() != null
                && entityType.GetDiscriminatorValue() is string value
                && value.Length > 0)
            {
                return value;
            }
        }

        return null;
    }

    public static Exception Unwrap(Exception ex) =>
        ex is TargetInvocationException invocation && invocation.InnerException != null
            ? Unwrap(invocation.InnerException)
            : ex;

    // Only names declared by PreviewErrorKind may be emitted; anything finer goes into `detail`.
    public static string Classify(Exception ex)
    {
        var message = ex.Message ?? "";
        if (message.Contains("could not be translated")) return "NotTranslatable";
        if (ex is MissingMethodException || ex is TypeLoadException || ex is System.IO.FileNotFoundException)
            return "ProviderVersionMismatch";
        if (ex is DbException) return "ProviderError";
        return "Unknown";
    }

    public static string Detail(Exception ex)
    {
        var message = ex.Message ?? "";
        if (message.Contains("No discriminators matched") || message.Contains("JSON object was expected"))
            return "SyntheticRowRejected";
        if (message.Contains("Sequence contains no elements")) return "EmptyResultSet";
        if (message.Contains("doesn't have as many fields")) return "ReaderTooNarrow";
        return null;
    }

    public static string ProviderShortName(string assemblyName) => assemblyName switch
    {
        "Microsoft.EntityFrameworkCore.SqlServer" => "SqlServer",
        "Microsoft.EntityFrameworkCore.Sqlite" => "Sqlite",
        "Npgsql.EntityFrameworkCore.PostgreSQL" => "PostgreSql",
        "Pomelo.EntityFrameworkCore.MySql" => "MySql",
        "MySql.EntityFrameworkCore" => "MySql",
        "Oracle.EntityFrameworkCore" => "Oracle",
        _ => "Unknown",
    };

    private static string Sanitize(string connectionString)
    {
        if (string.IsNullOrEmpty(connectionString)) return connectionString;
        var parts = connectionString.Split(';');
        for (int i = 0; i < parts.Length; i++)
        {
            var pair = parts[i].Split(new[] { '=' }, 2);
            if (pair.Length == 2)
            {
                var key = pair[0].Trim().ToLowerInvariant();
                if (key == "password" || key == "pwd") parts[i] = pair[0] + "=***";
            }
        }

        return string.Join(";", parts);
    }

    private sealed class Rung
    {
        public Rung(string name, int rows, string stringValue) { Name = name; Rows = rows; StringValue = stringValue; }
        public string Name;
        public int Rows;
        public string StringValue;
    }

    private sealed class Attempt
    {
        public string rung, error, errorKind, detail;
        public ResultInfo result;
        public List<CapturedCommand> commands = new();
    }
}

public sealed class Probe
{
    // Verified: 8 is too narrow for a ten-column split query, int.MaxValue throws OutOfMemoryException.
    public const int WideFieldCount = 1024;

    public int Rows = 1;
    public string StringValue = "";
    public IModel Model;
    public readonly List<CapturedCommand> Captured = new();

    public FakeReader NewReader() => new FakeReader(WideFieldCount, Rows, StringValue);

    public async Task<ResultInfo> ObserveAsync<T>(Func<Task<T>> f) => Describe(typeof(T), await f(), true);

    public ResultInfo Observe<T>(Func<T> f) => Describe(typeof(T), f(), false);

    public async Task<ResultInfo> ObserveVoidAsync(Func<Task> f) { await f(); return Describe(typeof(void), null, true); }

    public ResultInfo ObserveVoid(Action f) { f(); return Describe(typeof(void), null, false); }

    // A selection with no terminal operator emits no SQL until something enumerates it.
    public ResultInfo ObserveDeferred<T>(Func<IQueryable<T>> f)
    {
        var q = f();
        foreach (var _ in q) { }
        return Describe(typeof(IQueryable<T>), q, false);
    }

    public ResultInfo ObserveEnumerable<T>(Func<IEnumerable<T>> f)
    {
        var q = f();
        foreach (var _ in q) { }
        return Describe(typeof(IEnumerable<T>), q, false);
    }

    public async Task<ResultInfo> ObserveAsyncEnumerable<T>(Func<IAsyncEnumerable<T>> f)
    {
        var q = f();
        await foreach (var _ in q) { }
        return Describe(typeof(IAsyncEnumerable<T>), q, true);
    }

    private ResultInfo Describe(Type declared, object value, bool isAsync)
    {
        var info = new ResultInfo
        {
            isAsync = isAsync,
            declaredResultType = Pretty(declared),
            runtimeResultType = value == null ? null : Pretty(value.GetType()),
        };

        var t = declared;
        var element = t;

        if (t == typeof(void)) { info.shape = "Void"; info.elementType = null; info.elementKind = null; return info; }
        if (t == typeof(bool)) info.shape = "Boolean";
        else if (Is(t, typeof(List<>)) || Is(t, typeof(IList<>)) || Is(t, typeof(IReadOnlyList<>)) || Is(t, typeof(ICollection<>)))
        { info.shape = "List"; element = t.GetGenericArguments()[0]; }
        else if (t.IsArray) { info.shape = "Array"; element = t.GetElementType(); }
        else if (Is(t, typeof(Dictionary<,>)) || Is(t, typeof(IDictionary<,>)) || Is(t, typeof(IReadOnlyDictionary<,>)))
        { info.shape = "Dictionary"; info.keyType = Pretty(t.GetGenericArguments()[0]); element = t.GetGenericArguments()[1]; }
        else if (Is(t, typeof(HashSet<>)) || Is(t, typeof(ISet<>))) { info.shape = "HashSet"; element = t.GetGenericArguments()[0]; }
        else if (Is(t, typeof(ILookup<,>))) { info.shape = "Lookup"; info.keyType = Pretty(t.GetGenericArguments()[0]); element = t.GetGenericArguments()[1]; }
        else if (Is(t, typeof(IQueryable<>))) { info.shape = "DeferredQueryable"; element = t.GetGenericArguments()[0]; }
        else if (Is(t, typeof(IEnumerable<>))) { info.shape = "DeferredEnumerable"; element = t.GetGenericArguments()[0]; }
        else if (Is(t, typeof(IAsyncEnumerable<>))) { info.shape = "AsyncEnumerable"; element = t.GetGenericArguments()[0]; }
        else if (IsScalar(t)) info.shape = "Scalar";
        else info.shape = "SingleElement";

        info.elementType = Pretty(element);
        info.elementKind = KindOf(element);
        return info;
    }

    private static bool Is(Type t, Type definition) => t.IsGenericType && t.GetGenericTypeDefinition() == definition;

    private static bool IsScalar(Type t)
    {
        var u = Nullable.GetUnderlyingType(t) ?? t;
        return u.IsPrimitive || u.IsEnum || u == typeof(string) || u == typeof(decimal) || u == typeof(DateTime)
            || u == typeof(DateTimeOffset) || u == typeof(DateOnly) || u == typeof(TimeOnly) || u == typeof(TimeSpan)
            || u == typeof(Guid) || u == typeof(byte[]);
    }

    // context.Model.FindEntityType is the only reliable entity-versus-DTO oracle available at runtime.
    private string KindOf(Type t)
    {
        var u = Nullable.GetUnderlyingType(t) ?? t;
        if (IsScalar(u)) return "Scalar";
        if (Model != null && Model.FindEntityType(u) != null) return "Entity";
        if (u.IsGenericType && u.Name.Contains("AnonymousType")) return "Anonymous";
        if (u.IsGenericType && u.GetGenericTypeDefinition().Name.StartsWith("ValueTuple")) return "Tuple";
        if (u.IsGenericType && u.GetGenericTypeDefinition().Name.StartsWith("IGrouping")) return "Grouping";
        return "Dto";
    }

    public static string Pretty(Type t)
    {
        if (t == null) return null;
        var nullable = Nullable.GetUnderlyingType(t);
        if (nullable != null) return Pretty(nullable) + "?";
        if (t.IsArray) return Pretty(t.GetElementType()) + "[]";
        if (!t.IsGenericType) return Alias(t);
        var name = t.Name;
        var tick = name.IndexOf('`');
        if (tick > 0) name = name.Substring(0, tick);
        if (t.Name.Contains("AnonymousType")) name = "anonymous";
        return name + "<" + string.Join(", ", t.GetGenericArguments().Select(Pretty)) + ">";
    }

    private static string Alias(Type t) => t.FullName switch
    {
        "System.Int32" => "int",
        "System.Int64" => "long",
        "System.Int16" => "short",
        "System.Boolean" => "bool",
        "System.String" => "string",
        "System.Decimal" => "decimal",
        "System.Double" => "double",
        "System.Single" => "float",
        "System.Byte" => "byte",
        "System.Object" => "object",
        "System.Void" => "void",
        _ => t.Name,
    };
}

public static class ContextActivator
{
    public static DbContext Create(Type ctxType, CaptureInterceptor interceptor, Report report)
    {
        // A generated subclass exposes a static Pending field; it is the only way to reach a context that
        // picks its provider in OnConfiguring and has no DbContextOptions constructor to rebuild from.
        var pending = ctxType.GetField("Pending", BindingFlags.Public | BindingFlags.Static);
        if (pending != null && pending.FieldType == typeof(CaptureInterceptor))
        {
            pending.SetValue(null, interceptor);
            report.activationStrategy = "DerivedOnConfiguringContext";
            if (Preview.Dialect != null)
            {
                report.warnings.Add("This DbContext selects its provider in OnConfiguring, so the dialect picker cannot override it.");
            }

            return (DbContext)Activator.CreateInstance(ctxType);
        }

        // The design-time factory hard-codes a provider, so the dialect picker has to bypass it.
        if (Preview.Dialect == null)
        {
            var factoryInterface = typeof(IDesignTimeDbContextFactory<>).MakeGenericType(ctxType);
            var factoryType = AllTypes().FirstOrDefault(t => !t.IsAbstract && !t.IsInterface && factoryInterface.IsAssignableFrom(t));
            if (factoryType != null)
            {
                try
                {
                    var factory = Activator.CreateInstance(factoryType);
                    var produced = (DbContext)factoryInterface.GetMethod("CreateDbContext").Invoke(factory, new object[] { Array.Empty<string>() });
                    var rebuilt = Rebuild(produced, ctxType, interceptor);
                    produced.Dispose();
                    if (rebuilt != null) { report.activationStrategy = "DesignTimeFactory"; return rebuilt; }
                }
                catch (Exception ex)
                {
                    report.warnings.Add("IDesignTimeDbContextFactory failed: " + Preview.Unwrap(ex).Message);
                }
            }
        }

        DbContextOptions options;
        try { options = BuildOptions(ctxType, interceptor); }
        catch (Exception ex) { throw new PreviewActivationException(ctxType, Preview.Unwrap(ex)); }

        var ctors = ctxType.GetConstructors(BindingFlags.Public | BindingFlags.Instance | BindingFlags.NonPublic)
                           .OrderBy(c => c.GetParameters().Length).ToArray();

        var exact = ctors.FirstOrDefault(c => c.GetParameters().Length == 1 && c.GetParameters()[0].ParameterType.IsInstanceOfType(options));
        if (exact != null)
        {
            report.activationStrategy = "OptionsConstructor";
            try { return (DbContext)exact.Invoke(new object[] { options }); }
            catch (Exception ex) { throw new PreviewActivationException(ctxType, Preview.Unwrap(ex)); }
        }

        var withOptions = ctors.FirstOrDefault(c => c.GetParameters().Any(p => p.ParameterType.IsInstanceOfType(options)));
        if (withOptions != null)
        {
            var parameters = withOptions.GetParameters();
            var arguments = parameters.Select(p => p.ParameterType.IsInstanceOfType(options) ? options : Stub.Make(p.ParameterType)).ToArray();
            report.activationStrategy = "OptionsConstructorWithStubbedDependencies";
            var extras = parameters.Where(p => !p.ParameterType.IsInstanceOfType(options)).Select(p => p.ParameterType.Name).ToArray();
            if (extras.Length > 0)
            {
                report.warnings.Add("The DbContext constructor also requires " + string.Join(", ", extras) + "; stub instances were supplied.");
            }

            try { return (DbContext)withOptions.Invoke(arguments); }
            catch (Exception ex) { throw new PreviewActivationException(ctxType, Preview.Unwrap(ex)); }
        }

        throw new PreviewActivationException(ctxType, new InvalidOperationException("No DbContextOptions constructor was found."));
    }

    private static DbContextOptions BuildOptions(Type ctxType, CaptureInterceptor interceptor)
    {
        var builderType = typeof(DbContextOptionsBuilder<>).MakeGenericType(ctxType);
        var builder = (DbContextOptionsBuilder)Activator.CreateInstance(builderType);
        Preview.ConfigureProvider(builder);
        builder.AddInterceptors(interceptor);
        builder.ConfigureWarnings(w => w.Ignore(CoreEventId.ManyServiceProvidersCreatedWarning));

        // DbContextOptionsBuilder<T>.Options hides the base member, so reflecting on "Options" throws
        // AmbiguousMatchException; the base property already returns DbContextOptions<T>.
        return builder.Options;
    }

    private static DbContext Rebuild(DbContext existing, Type ctxType, CaptureInterceptor interceptor)
    {
        try
        {
            var resolved = existing.GetService<IDbContextOptions>();
            var builderType = typeof(DbContextOptionsBuilder<>).MakeGenericType(ctxType);
            var builder = (DbContextOptionsBuilder)Activator.CreateInstance(builderType, resolved);
            builder.AddInterceptors(interceptor);
            builder.ConfigureWarnings(w => w.Ignore(CoreEventId.ManyServiceProvidersCreatedWarning));
            var options = builder.Options;
            var ctor = ctxType.GetConstructors()
                .FirstOrDefault(c => c.GetParameters().Length == 1 && c.GetParameters()[0].ParameterType.IsInstanceOfType(options));
            return ctor == null ? null : (DbContext)ctor.Invoke(new object[] { options });
        }
        catch
        {
            return null;
        }
    }

    public static IEnumerable<Type> AllTypes()
    {
        LoadNeighbouringAssemblies();
        return AppDomain.CurrentDomain.GetAssemblies()
            .Where(a => !a.IsDynamic)
            .SelectMany(a => { try { return a.GetTypes(); } catch { return Array.Empty<Type>(); } });
    }

    // Referenced assemblies load lazily, so a design-time factory in a project whose types the query never
    // mentions would otherwise be invisible.
    public static void LoadNeighbouringAssemblies()
    {
        try
        {
            var baseDirectory = AppContext.BaseDirectory;
            if (string.IsNullOrEmpty(baseDirectory)) return;
            foreach (var file in System.IO.Directory.GetFiles(baseDirectory, "*.dll"))
            {
                try { Assembly.LoadFrom(file); } catch { }
            }
        }
        catch { }
    }
}

public sealed class PreviewActivationException : Exception
{
    public PreviewActivationException(Type type, Exception inner)
        : base("Could not construct '" + type.FullName + "': " + inner.Message
               + " Add an IDesignTimeDbContextFactory<" + type.Name + "> to the project -- the same hook `dotnet ef` uses -- "
               + "and EF Core SQL Preview will use it.", inner)
    {
    }
}

public static class Stub
{
    // Passing null for a constructor's other dependencies is not enough: a context that reads a property off
    // an injected service throws NullReferenceException before EF is ever reached.
    public static object Make(Type t)
    {
        if (t.IsValueType) return Activator.CreateInstance(t);
        if (t == typeof(string)) return "";
        if (t.IsInterface)
        {
            try
            {
                var create = typeof(DispatchProxy).GetMethods(BindingFlags.Public | BindingFlags.Static)
                    .First(m => m.Name == "Create" && m.IsGenericMethodDefinition && m.GetGenericArguments().Length == 2);
                return create.MakeGenericMethod(t, typeof(NullProxy)).Invoke(null, Array.Empty<object>());
            }
            catch { return null; }
        }

        if (!t.IsAbstract)
        {
            try { return Activator.CreateInstance(t, nonPublic: true); } catch { }
        }

        return null;
    }
}

public class NullProxy : DispatchProxy
{
    protected override object Invoke(MethodInfo method, object[] arguments)
    {
        var returnType = method.ReturnType;
        if (returnType == typeof(void)) return null;
        if (returnType == typeof(string)) return "";
        if (returnType.IsValueType) return Activator.CreateInstance(returnType);
        return null;
    }
}

public sealed class CaptureInterceptor : DbConnectionInterceptor, IDbCommandInterceptor
{
    private readonly Probe _probe;

    public CaptureInterceptor(Probe probe) => _probe = probe;

    public override InterceptionResult ConnectionOpening(DbConnection c, ConnectionEventData e, InterceptionResult r) => InterceptionResult.Suppress();
    public override ValueTask<InterceptionResult> ConnectionOpeningAsync(DbConnection c, ConnectionEventData e, InterceptionResult r, CancellationToken ct = default) => new(InterceptionResult.Suppress());
    public override InterceptionResult ConnectionClosing(DbConnection c, ConnectionEventData e, InterceptionResult r) => InterceptionResult.Suppress();
    public override ValueTask<InterceptionResult> ConnectionClosingAsync(DbConnection c, ConnectionEventData e, InterceptionResult r) => new(InterceptionResult.Suppress());

    public InterceptionResult<DbDataReader> ReaderExecuting(DbCommand c, CommandEventData e, InterceptionResult<DbDataReader> r)
    { Capture(c); return InterceptionResult<DbDataReader>.SuppressWithResult(_probe.NewReader()); }

    public ValueTask<InterceptionResult<DbDataReader>> ReaderExecutingAsync(DbCommand c, CommandEventData e, InterceptionResult<DbDataReader> r, CancellationToken ct = default)
    { Capture(c); return new(InterceptionResult<DbDataReader>.SuppressWithResult(_probe.NewReader())); }

    public InterceptionResult<int> NonQueryExecuting(DbCommand c, CommandEventData e, InterceptionResult<int> r)
    { Capture(c); return InterceptionResult<int>.SuppressWithResult(0); }

    public ValueTask<InterceptionResult<int>> NonQueryExecutingAsync(DbCommand c, CommandEventData e, InterceptionResult<int> r, CancellationToken ct = default)
    { Capture(c); return new(InterceptionResult<int>.SuppressWithResult(0)); }

    public InterceptionResult<object> ScalarExecuting(DbCommand c, CommandEventData e, InterceptionResult<object> r)
    { Capture(c); return InterceptionResult<object>.SuppressWithResult(null); }

    public ValueTask<InterceptionResult<object>> ScalarExecutingAsync(DbCommand c, CommandEventData e, InterceptionResult<object> r, CancellationToken ct = default)
    { Capture(c); return new(InterceptionResult<object>.SuppressWithResult(null)); }

    private void Capture(DbCommand command)
    {
        var captured = new CapturedCommand { sql = Normalize(command.CommandText), commandType = command.CommandType.ToString() };
        foreach (DbParameter p in command.Parameters)
        {
            var isNull = p.Value is null || p.Value == DBNull.Value;
            captured.parameters.Add(new CapturedParameter
            {
                name = p.ParameterName,
                dbType = SafeDbType(p),
                clrType = isNull ? null : Probe.Pretty(p.Value.GetType()),
                value = ValueRenderer.Render(p.Value),
                isNull = isNull,
                size = p.Size,
                direction = p.Direction.ToString(),
            });
        }

        _probe.Captured.Add(captured);
    }

    private static string SafeDbType(DbParameter p)
    {
        try { return p.DbType.ToString(); } catch { return null; }
    }

    // EF emits CRLF on Windows; normalising makes the tool window line-ending agnostic. Nothing else is
    // reformatted: EF's own layout is already readable and re-flowing risks mangling string literals.
    private static string Normalize(string sql) => sql?.Replace("\r\n", "\n").Replace("\r", "\n").Trim();
}

public static class ValueRenderer
{
    public static string Render(object v)
    {
        if (v is null || v == DBNull.Value) return null;
        switch (v)
        {
            case string s: return s;
            case bool b: return b ? "true" : "false";
            case byte[] bytes:
                var head = bytes.Length > 32 ? bytes.AsSpan(0, 32).ToArray() : bytes;
                return "0x" + Convert.ToHexString(head) + (bytes.Length > 32 ? "…" : "");
            case DateTime dt: return dt.ToString("O", CultureInfo.InvariantCulture);
            case DateTimeOffset dto: return dto.ToString("O", CultureInfo.InvariantCulture);
            // Npgsql sends a whole collection as a single array parameter rather than expanding it.
            case IEnumerable e: return "[" + string.Join(", ", e.Cast<object>().Take(64).Select(Render)) + "]";
            default: return Convert.ToString(v, CultureInfo.InvariantCulture);
        }
    }
}

public sealed class FakeReader : DbDataReader
{
    private int _rowsLeft;
    private readonly int _fields;
    private readonly string _stringValue;

    public FakeReader(int fields, int rows, string stringValue)
    {
        _fields = fields;
        _rowsLeft = rows;
        _stringValue = stringValue ?? "";
    }

    public override int FieldCount => _fields;
    public override bool HasRows => _rowsLeft > 0;
    public override bool IsClosed => false;
    public override int RecordsAffected => 0;
    public override int Depth => 0;
    public override bool Read() { if (_rowsLeft > 0) { _rowsLeft--; return true; } return false; }
    public override Task<bool> ReadAsync(CancellationToken ct) => Task.FromResult(Read());
    public override bool NextResult() => false;
    public override Task<bool> NextResultAsync(CancellationToken ct) => Task.FromResult(false);
    public override IEnumerator GetEnumerator() => Array.Empty<object>().GetEnumerator();
    public override string GetName(int i) => "c" + i;
    public override int GetOrdinal(string name) => 0;
    public override Type GetFieldType(int i) => typeof(object);
    public override string GetDataTypeName(int i) => "int";
    public override bool IsDBNull(int i) => false;
    public override Task<bool> IsDBNullAsync(int i, CancellationToken ct) => Task.FromResult(false);
    public override object this[int i] => GetValue(i);
    public override object this[string name] => GetValue(0);
    public override bool GetBoolean(int i) => false;
    public override byte GetByte(int i) => 0;
    public override long GetBytes(int i, long o, byte[] b, int bo, int l) => 0;
    public override char GetChar(int i) => ' ';
    public override long GetChars(int i, long o, char[] b, int bo, int l) => 0;
    public override DateTime GetDateTime(int i) => new DateTime(2000, 1, 1);
    public override decimal GetDecimal(int i) => 0m;
    public override double GetDouble(int i) => 0d;
    public override float GetFloat(int i) => 0f;
    public override Guid GetGuid(int i) => Guid.Empty;
    public override short GetInt16(int i) => 0;
    public override int GetInt32(int i) => 0;
    public override long GetInt64(int i) => 0;
    public override string GetString(int i) => _stringValue;
    public override object GetValue(int i) => 0;
    public override int GetValues(object[] values) { for (int i = 0; i < values.Length; i++) values[i] = 0; return values.Length; }
    public override System.IO.TextReader GetTextReader(int i) => new System.IO.StringReader(_stringValue);
    public override System.IO.Stream GetStream(int i) => new System.IO.MemoryStream(Encoding.UTF8.GetBytes(_stringValue));
    public override T GetFieldValue<T>(int i) => (T)Fallback(typeof(T), _stringValue);
    public override Task<T> GetFieldValueAsync<T>(int i, CancellationToken ct) => Task.FromResult((T)Fallback(typeof(T), _stringValue));

    private static object Fallback(Type t, string stringValue)
    {
        if (t == typeof(string)) return stringValue;
        if (t == typeof(byte[])) return Array.Empty<byte>();
        if (t == typeof(object)) return 0;
        var underlying = Nullable.GetUnderlyingType(t);
        if (underlying != null) return Activator.CreateInstance(underlying);
        if (t.IsValueType) return Activator.CreateInstance(t);
        try { return Activator.CreateInstance(t); } catch { return null; }
    }
}

public sealed class Report
{
    public bool success { get; set; }
    public int schemaVersion { get; set; } = 1;
    public string provider { get; set; } = "Unknown";
    public string providerAssembly { get; set; }
    public string efCoreVersion { get; set; } = typeof(DbContext).Assembly.GetName().Version?.ToString();
    public string contextType { get; set; }
    public string activationStrategy { get; set; }
    public string captureMode { get; set; }
    public string connectionString { get; set; }
    public List<CapturedCommand> commands { get; set; } = new();
    public ResultInfo result { get; set; }
    public List<string> warnings { get; set; } = new();
    public string error { get; set; }
    public string errorKind { get; set; } = "None";
}

public sealed class CapturedCommand
{
    public string sql { get; set; }
    public string commandType { get; set; }
    public List<CapturedParameter> parameters { get; set; } = new();
}

public sealed class CapturedParameter
{
    public string name { get; set; }
    public string dbType { get; set; }
    public string clrType { get; set; }
    public string value { get; set; }
    public bool isNull { get; set; }
    public int size { get; set; }
    public string direction { get; set; }
}

public sealed class ResultInfo
{
    public bool isAsync { get; set; }
    public string shape { get; set; }
    public string elementType { get; set; }
    public string elementKind { get; set; }
    public string keyType { get; set; }
    public string declaredResultType { get; set; }
    public string runtimeResultType { get; set; }
}
""";

    /// <summary>
    /// A worker that only enumerates the <c>DbContext</c> types reachable from the user's project.
    /// </summary>
    /// <remarks>
    /// The real worker has to cast the activated context to a compile-time type before the query will bind,
    /// so when the analyzer could not name that type this program runs first and reports the candidates.
    /// </remarks>
    public const string DiscoverySource = """
// <auto-generated> EF Core SQL Preview context discovery. Regenerated on every run; do not edit. </auto-generated>
{{PROJECT_DIRECTIVES}}
{{PACKAGE_DIRECTIVES}}
{{PROPERTY_DIRECTIVES}}

using System.Reflection;
using System.Text;
using System.Text.Json;
using Microsoft.EntityFrameworkCore;

var __efspCandidates = Discovery.Find();
var __efspReport = new Report
{
    success = false,
    errorKind = "ContextActivationFailed",
    contextType = __efspCandidates.Count == 1 ? __efspCandidates[0] : null,
    error = __efspCandidates.Count == 0
        ? "No DbContext type was found in the referenced projects. Open the query's project and check that it references the project holding your DbContext."
        : "The DbContext type could not be determined from the selection. Choose one of the candidates listed in the warnings and re-run.",
};
foreach (var __efspCandidate in __efspCandidates)
{
    __efspReport.warnings.Add("EFSP-CONTEXT-CANDIDATE: " + __efspCandidate);
}

Discovery.Emit(__efspReport);
return 0;

public static class Discovery
{
    public const string Begin = "<<<EFSQLPREVIEW-BEGIN>>>";
    public const string End = "<<<EFSQLPREVIEW-END>>>";

    public static List<string> Find()
    {
        try
        {
            foreach (var file in System.IO.Directory.GetFiles(AppContext.BaseDirectory, "*.dll"))
            {
                try { Assembly.LoadFrom(file); } catch { }
            }
        }
        catch { }

        var results = new List<string>();
        foreach (var assembly in AppDomain.CurrentDomain.GetAssemblies().Where(a => !a.IsDynamic))
        {
            Type[] types;
            try { types = assembly.GetTypes(); } catch { continue; }
            foreach (var type in types)
            {
                if (type.IsAbstract || !type.IsPublic || !typeof(DbContext).IsAssignableFrom(type)) continue;
                if (type == typeof(DbContext)) continue;
                if (type.Namespace != null && type.Namespace.StartsWith("Microsoft.EntityFrameworkCore")) continue;
                if (!results.Contains(type.FullName)) results.Add(type.FullName);
            }
        }

        results.Sort(StringComparer.Ordinal);
        return results;
    }

    public static void Emit(Report report)
    {
        try { Console.OutputEncoding = Encoding.UTF8; } catch { }
        var json = JsonSerializer.Serialize(report, new JsonSerializerOptions
        {
            WriteIndented = false,
            Encoder = System.Text.Encodings.Web.JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
        });
        Console.Out.Write(Begin);
        Console.Out.Write(json);
        Console.Out.Write(End);
        Console.Out.WriteLine();
        Console.Out.Flush();
    }
}

public sealed class Report
{
    public bool success { get; set; }
    public int schemaVersion { get; set; } = 1;
    public string provider { get; set; } = "Unknown";
    public string contextType { get; set; }
    public List<string> warnings { get; set; } = new();
    public string error { get; set; }
    public string errorKind { get; set; } = "None";
}
""";
}
